[package]
name = "graphlib2"
version = "0.1.1"
edition = "2018"

[lib]
name = "graphlib2"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module", "abi3-py37"]

[dependencies.pyo3-build-config]
version = "0.15.1"

[dependencies]
nohash-hasher = "0.2.0"
seahash = "4.1.0"

[package.metadata.maturin]
python-source = "python"
