
[project]
name = "graphlib2"
repository = "https://github.com/adriangb/graphlib2"
description = "Rust port of the Python stdlib graphlib modules"
authors = [
    {name = "Adrian Garcia Badaracco"}
]
readme = { file = "README.md" }
documentation = "https://github.com/adriangb/README.md"
license = {file = "LICENSE.txt"}
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "typing-extensions>=3; python_version < '3.8'",
]

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[tool.maturin]
sdist-include = ["Cargo.lock"]
strip = true

[tool.isort]
profile = "black"
